# Generated by Django 2.2.5 on 2019-09-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='values',
            new_name='Value',
        ),
    ]
