# Generated by Django 2.2.5 on 2019-09-28 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20190927_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='value',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
