# Generated by Django 2.2.5 on 2019-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20190928_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='mq135',
        ),
        migrations.RemoveField(
            model_name='value',
            name='mq2',
        ),
        migrations.RemoveField(
            model_name='value',
            name='mq4',
        ),
        migrations.AddField(
            model_name='value',
            name='alcohol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='ammonia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='carbon_dioxide',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='carbon_monoxide',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='lpg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='methane',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='propane',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='value',
            name='smoke',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='value',
            name='dust',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='value',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='value',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
